name: Crash
description: The game has a problem when FalsePatternLib is present
title: "[Bug]: "
labels: ["bug"]
assignees:
  - falsepattern
body:
# Recommended for precise context
  - type: input
    id: modpack
    attributes:
      label: Modpack (Optional)
      description: If you used the mod in a modpack, you should include the pack's exact name and version here to make debugging easier.
    validations:
      required: false
# Essential
  - type: textarea
    id: logs
    attributes:
      label: Game log
      description: Attach the fml-client-latest.log file here.
    validations:
      required: true
# Essential
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how and when you experience this bug.
    validations:
      required: false