name: Compatibility Request
description: If you tested FalsePatternLib with another mod and it crashes or has weird bugs, you can ask for a compatibility patch through this.
title: "[Compatibility Request]: "
labels: ["compat-request"]
assignees:
  - falsepattern
body:
  # Essential
  - type: input
    id: modname
    attributes:
      label: Other mod's name
      description: The name of the other mod
    validations:
      required: true
# Essential
  - type: input
    id: modurl
    attributes:
      label: Other mod's homepage
      description: A link to the main site where the other mod is hosted. Preferrably the original website of a mod, but a modrinth/curseforge/whatever page is also acceptable. Do not post a raw download link, those requests will be ignored.
    validations:
      required: true
# Important
  - type: dropdown
    id: license
    attributes:
      label: Other mod's license
      description: What license does the other mod have? (Open source mods are easier to write compatibility patches for)
      options:
        - AGPLv3
        - AGPLv2
        - GPLv3
        - GPLv2
        - LGPLv3
        - LGPLv2
        - Apache 2.0
        - Beerware
        - BSD 3-Clause
        - BSD 2-Clause
        - EPL 2.0
        - MIT
        - MPL 2.0
        - Unlicense
        - WTFPL
        - Other open source license (please specify in the description)
        - All Rights Reserved
    validations:
      required: true
# Recommended
  - type: textarea
    id: logs
    attributes:
      label: Game log
      description: Attach the fml-client-latest.log file here.
    validations:
      required: true
# Recommended
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe any visual errors that appear, and attach screenshots of them. You can leave this empty if it's a crash without any visible stuff.
    validations:
      required: false
# Modify this after every added patch
#  - type: checkboxes
#    id: existingpatches
#    attributes:
#      label: Existing Patches
#      description: The mods below already have compatibility patches. If you're experiencing issues with those, submit either a crash or a bug report!
#      options:
#        - label: This request is not for X
#          required: true
#        - label: This request is not for Y
#          required: true
#        - label: This request is not for Z
#          required: true